// <auto-generated />
using System;
using ControlPlane.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ControlPlane.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ControlPlaneDbContext))]
    [Migration("20260810115733_AddModelUsage")]
    partial class AddModelUsage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("ControlPlane.Domain.HookEvents.HookEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("AgentId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("agent_id");

                    b.Property<string>("AgentType")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("agent_type");

                    b.Property<int?>("CacheCreationTokens")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cache_creation_tokens");

                    b.Property<int?>("CacheReadTokens")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cache_read_tokens");

                    b.Property<string>("Cwd")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT")
                        .HasColumnName("cwd");

                    b.Property<int?>("DurationMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("duration_ms");

                    b.Property<string>("Effort")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("effort");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT")
                        .HasColumnName("error");

                    b.Property<string>("EventName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("event_name");

                    b.Property<int?>("InputTokens")
                        .HasColumnType("INTEGER")
                        .HasColumnName("input_tokens");

                    b.Property<int?>("OutputTokens")
                        .HasColumnType("INTEGER")
                        .HasColumnName("output_tokens");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("payload");

                    b.Property<bool>("PayloadTruncated")
                        .HasColumnType("INTEGER")
                        .HasColumnName("payload_truncated");

                    b.Property<string>("PermissionMode")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("permission_mode");

                    b.Property<string>("Project")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("project");

                    b.Property<string>("PromptId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("prompt_id");

                    b.Property<DateTime>("ReceivedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("received_at_utc");

                    b.Property<string>("SessionId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("session_id");

                    b.Property<string>("Source")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("source");

                    b.Property<string>("StopReason")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("stop_reason");

                    b.Property<string>("ToolName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("tool_name");

                    b.Property<string>("ToolUseId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("tool_use_id");

                    b.HasKey("Id")
                        .HasName("pk_hook_events");

                    b.HasIndex("AgentType")
                        .HasDatabaseName("ix_hook_events_agent_type");

                    b.HasIndex("EventName")
                        .HasDatabaseName("ix_hook_events_event_name");

                    b.HasIndex("Project")
                        .HasDatabaseName("ix_hook_events_project");

                    b.HasIndex("ReceivedAtUtc")
                        .IsDescending()
                        .HasDatabaseName("ix_hook_events_received_at_utc");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_hook_events_session_id");

                    b.HasIndex("ToolName")
                        .HasDatabaseName("ix_hook_events_tool_name");

                    b.ToTable("hook_events", (string)null);
                });

            modelBuilder.Entity("ControlPlane.Domain.ModelUsages.ModelUsage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("AgentId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("agent_id");

                    b.Property<string>("AgentType")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("agent_type");

                    b.Property<int>("CacheCreationTokens")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cache_creation_tokens");

                    b.Property<int>("CacheReadTokens")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cache_read_tokens");

                    b.Property<int>("InputTokens")
                        .HasColumnType("INTEGER")
                        .HasColumnName("input_tokens");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("message_id");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("model");

                    b.Property<int>("OutputTokens")
                        .HasColumnType("INTEGER")
                        .HasColumnName("output_tokens");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("session_id");

                    b.Property<int?>("SpawnDepth")
                        .HasColumnType("INTEGER")
                        .HasColumnName("spawn_depth");

                    b.Property<string>("StopReason")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("stop_reason");

                    b.Property<string>("TaskDescription")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT")
                        .HasColumnName("task_description");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("timestamp_utc");

                    b.HasKey("Id")
                        .HasName("pk_model_usages");

                    b.HasIndex("AgentType")
                        .HasDatabaseName("ix_model_usages_agent_type");

                    b.HasIndex("MessageId")
                        .IsUnique()
                        .HasDatabaseName("ix_model_usages_message_id");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_model_usages_session_id");

                    b.ToTable("model_usages", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
