// <auto-generated />
using System;
using ControlPlane.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ControlPlane.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ControlPlaneDbContext))]
    partial class ControlPlaneDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("ControlPlane.Domain.HookEvents.HookEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("AgentId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("agent_id");

                    b.Property<string>("AgentType")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("agent_type");

                    b.Property<int?>("CacheCreationTokens")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cache_creation_tokens");

                    b.Property<int?>("CacheReadTokens")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cache_read_tokens");

                    b.Property<string>("Cwd")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT")
                        .HasColumnName("cwd");

                    b.Property<int?>("DurationMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("duration_ms");

                    b.Property<string>("Effort")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("effort");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT")
                        .HasColumnName("error");

                    b.Property<string>("EventName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("event_name");

                    b.Property<int?>("InputTokens")
                        .HasColumnType("INTEGER")
                        .HasColumnName("input_tokens");

                    b.Property<int?>("OutputTokens")
                        .HasColumnType("INTEGER")
                        .HasColumnName("output_tokens");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("payload");

                    b.Property<bool>("PayloadTruncated")
                        .HasColumnType("INTEGER")
                        .HasColumnName("payload_truncated");

                    b.Property<string>("PermissionMode")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("permission_mode");

                    b.Property<string>("Project")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("project");

                    b.Property<string>("PromptId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("prompt_id");

                    b.Property<DateTime>("ReceivedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("received_at_utc");

                    b.Property<string>("SessionId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("session_id");

                    b.Property<string>("Source")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("source");

                    b.Property<string>("StopReason")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("stop_reason");

                    b.Property<string>("ToolName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("tool_name");

                    b.Property<string>("ToolUseId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("tool_use_id");

                    b.HasKey("Id")
                        .HasName("pk_hook_events");

                    b.HasIndex("AgentType")
                        .HasDatabaseName("ix_hook_events_agent_type");

                    b.HasIndex("EventName")
                        .HasDatabaseName("ix_hook_events_event_name");

                    b.HasIndex("Project")
                        .HasDatabaseName("ix_hook_events_project");

                    b.HasIndex("ReceivedAtUtc")
                        .IsDescending()
                        .HasDatabaseName("ix_hook_events_received_at_utc");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_hook_events_session_id");

                    b.HasIndex("ToolName")
                        .HasDatabaseName("ix_hook_events_tool_name");

                    b.ToTable("hook_events", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
